services:
  drawio:
    build: .
    ports:
      - "18080:8080"
    volumes:
      - ./plugins:/usr/local/tomcat/webapps/draw/plugins
    environment:
      - DRAWIO_SELF_CONTAINED=1
    restart: unless-stopped
